plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"mcadvanced" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs {
		server {
			vmArg "-Xmx420m"
			vmArg "-XX:MaxMetaspaceSize=200m"
			vmArg "-XX:+UseSerialGC"
			vmArg "-Dio.netty.allocator.maxOrder=1"
		}
		client {
			vmArg "-Xmx480m"
			vmArg "-XX:MaxMetaspaceSize=256m"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}
